---
title: "Sex biased mutation rate"
author: "Isobel Beasley"
date: "2021-12-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup}
# only look at public sheets - so no authentication is needed
googlesheets4::gs4_deauth()

# read in sex bias mutation data.frame
sex_bias_mut_df = googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/10ZVgeGlDpEnPG-4zLLrSBQjF7p2_9hzzIMPuIRuvogg/edit#gid=537547888", range = "Alpha Estimates (each row is a single estimate)")

head(sex_bias_mut_df)

library(ggplot2)
library(dplyr)

# Set up custom theme for ggplots
custom_theme <-
  list(
    theme_bw() +
      theme(
        panel.border = element_blank(),
        axis.line = element_line(),
        text = element_text(size = 25),
        legend.position = "bottom",
        strip.background = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)
      )
  )

```

## Distribution of sex-biased mutation estimates

```{r dist_sex_est, fig.height = 8, fig.width = 10}

sex_bias_mut_df %>% 
  ggplot(aes(x=alpha_point_estimate)) + 
  geom_histogram() + 
  labs(title = "Distribution of estimated sex-biased mutation rate",
        x = "Point estimate of the male-biased mutation rate (alpha)",
       y= "Count") + 
  custom_theme + 
  geom_vline(xintercept = 1, col = "red", linetype = 2) + 
  annotate(
  "text",
  x = 5,
  y = 40,
  size = 9,
  hjust = 0,
  col = "red", 
  label = "Line of equal mutation rate across the sexes"
)

summary(sex_bias_mut_df$alpha_point_estimate)

sex_bias_mut_df %>% 
  ggplot(aes(x=alpha_point_estimate)) +
  geom_boxplot() + 
  custom_theme

```